version: '3.7'

services:
  mongo:
    image: mongo:latest
    container_name: wishlist
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: wishlist
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
volumes:
  mongo_data: